

# Name your project! Project names should contain only lowercase characters
# and underscores. A good package name should reflect your organization's
# name or the intended use of these models
name: 'DBT_Mouritech'
version: '1.0.0'
config-version: 2


# This setting configures which "profile" dbt uses for this project.
profile: 'default'


# These configurations specify where dbt should look for different types of files.
# The `source-paths` config, for example, states that models in this project can be
# found in the "models/" directory. You probably won't need to change these!
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]


target-path: "target"  # directory which will store compiled SQL files
clean-targets:         # directories to be removed by `dbt clean`
 - "target"
 - "dbt_packages"




# Configuring models
# Full documentation: https://docs.getdbt.com/docs/configuring-models


# In this example config, we tell dbt to build all models in the example/ directory
# as tables. These settings can be overridden in the individual model files
# using the `{{ config(...) }}` macro.
models:
 DBT_Mouritech:
   +materialized: table
   app:
     hr:
       +materialized: table
       +schema:  app
       +database: |
         {%- if target.name == "default" -%} dbt_dev
         {%- elif target.name == "dev" -%} dbt_dev
         {%- elif target.name == "qa" -%} dbt_qa
         {%- elif target.name == "prd" -%} dbt_prd
         {%- else -%} invalid_target_name_please_check
         {%- endif -%}


   edw:
     +materialized: table
     +schema:  edw
     +database: |
       {%- if target.name == "default" -%} dbt_dev
       {%- elif target.name == "dev" -%} dbt_dev
       {%- elif target.name == "qa" -%} dbt_qa
       {%- elif target.name == "prd" -%} dbt_prd
       {%- else -%} invalid_target_name_please_check
       {%- endif -%}

   stg:
     +materialized: table
     +schema:  stg
     +database: |
       {%- if target.name == "default" -%} dbt_dev
       {%- elif target.name == "dev" -%} dbt_dev
       {%- elif target.name == "qa" -%} dbt_qa
       {%- elif target.name == "prd" -%} dbt_prd
       {%- else -%} invalid_target_name_please_check
       {%- endif -%}


   example:
     +materialized: view
     +schema:  stg
     +database: |
       {%- if target.name == "default" -%} dbt_dev
       {%- elif target.name == "dev" -%} dbt_dev
       {%- elif target.name == "qa" -%} dbt_qa
       {%- elif target.name == "prd" -%} dbt_prd
       {%- else -%} invalid_target_name_please_check
       {%- endif -%}


seeds:
 +schema: src
 +quote_columns: false
 +database: |
   {%- if target.name == "default" -%} dbt_dev
   {%- elif target.name == "dev" -%} dbt_dev
   {%- elif target.name == "qa" -%} dbt_qa
   {%- elif target.name == "prd" -%} dbt_prd
   {%- else -%} invalid_target_name_please_check
   {%- endif -%}


snapshots:
 +target_schema: edw
 +target_database: |
   {%- if target.name == "default" -%} dbt_dev
   {%- elif target.name == "dev" -%} dbt_dev
   {%- elif target.name == "qa" -%} dbt_qa
   {%- elif target.name == "prd" -%} dbt_prd
   {%- else -%} invalid_target_name_please_check
   {%- endif -%}

